### ISSUE TITLE
Adonis V6 Support

### ISSUE THREAD

**Issue by jbarretodev** [verful/adonis-scheduler#69] opened 2024-04-11 13:04 UTC
![image](https://github.com/verful/adonis-scheduler/assets/64809357/a6728153-c9a7-4808-8ad8-57c0145fbdf4)

**Comment by arthur-er** [comment] 2024-04-12 23:15
Package not ready for V6, duplicate of #61

**Closed as completed** 2024-04-12 23:16 UTC
